run_mode: "pipeline"
version: "v1"

#logistic Regression
model_type: "logreg"
param_grid:
  penalty: ["l2"]
  C: [0.1] #, 1.0, 10.0]
  max_iter: [1000]

# CART
#model_type: "cart"
#param_grid:
#  max_depth: [5, 10, 20]
#  min_samples_split: [2, 10, 50]

 # Random Forest
#model_type: "rf"
#param_grid:
#  n_estimators: [100, 200]
#  max_depth: [10, 20]
#  min_samples_split: [2,5]

# XGBoost
#model_type: "xgb"
#param_grid:
#  n_estimators: [100, 200]
#  max_depth: [5, 10]
#  learning_rate: [0.05, 0.1]