model_type: "xgb"
param_grid:
  n_estimators: [100, 200]
  max_depth: [5, 7]
  learning_rate: [0.05, 0.1]
params: {}
run_mode: "pipeline"
version: "final-v1"
retrain_mode: false

# LOGREG
#model_type: "logreg"
#param_grid:
#  penalty: ["l2"]
#  solver: [ "liblinear" ]        # <- supports l2 + C
#  C: [0.1] #, 1.0, 10.0]
#  max_iter: [1000]
#params: {}
#run_mode: "pipeline"
#version: "v1"
#retrain_mode: false


# CART
#model_type: "cart"
#param_grid:
#  max_depth: [5, 10, 20]
#  min_samples_split: [2, 10, 50]

# Random Forest
#model_type: "rf"
#param_grid:
#  n_estimators: [100, 200]
#  max_depth: [10, 20]
#  min_samples_split: [2,5]


#retrain_mode: true
#model_type: "xgboost"
#version: "v2"
#run_mode: "retrain"