name: Self-hosted runner test (Serving EC2)
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, ml, ec2]   # must match the runner's labels on the serving box
    steps:
      - name: Show runner info
        run: |
          echo "CONNECTED (self-hosted)"
          echo "whoami: $(whoami)"
          echo "hostname: $(hostname)"
          echo "uname: $(uname -a)"
          which python || true
          which aws || true
          systemctl is-active mlflow || echo "mlflow not running here (expected if only serving)"
